# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

version: 2.7.2.{build}-alpha
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
branches:  
  only:
  - develop
install:
- cmd: nuget sources add -Name VVVV -Source http://vvvv.org:8111/guestAuth/app/nuget/v1/FeedService.svc/
cache: 
- src/packages -> **\packages.config
- copy -> copy
#- '%LocalAppData%\NuGet\Cache'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore src/vvvv-Message.sln -verbosity detailed
build:
  project: src/vvvv-Message.sln
  publish_wap: true
  verbosity: quiet
after_build:
- ps: nuget pack src/MessageCore/SharpMessage.nuspec
test: off
artifacts:
- path: build/AnyCPU/$(configuration)
  name: vvvv-Message
  type: WebDeployPackage
- path: build/AnyCPU/$(configuration)/core/VVVV.Packs.Messaging.dll
  name: dll
- path: '**\SharpMessage*.nupkg'
  name: SharpMessage
  type: NuGetPackage
deploy:
- provider: GitHub
  draft: true
  description: Automatic Deployment powered by AppVeyor
  auth_token:
    secure: GMMqt9Z8X4poG9NQFBGrbi4hiVnj5Qc1XIWmfl0rdqi8mJevjvECGKRlyIYy07aO
  artifact: vvvv-Message dll
  prerelease: true
  on:
    branch: develop                 # release from develop branch only
    appveyor_repo_tag: false        # deploy on tag push only
- provider: NuGet
  api_key:
    secure: 0hhwaeSEUfUNsjinrtuxpRwIAhwnpo4CdmcVd9nQtxh6kdSLnU1jJkPVRW+sDxkS
  skip_symbols: true
  artifact: SharpMessage